name: Build and Publish ESP32 Firmware

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
  #   paths:
  #     - '**/*.ino'
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core 3.0.4
        run: |
          arduino-cli config init
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.0.4

      #- name: Install libraries
      #  run: |
      #    arduino-cli lib install --git-url https://github.com/allanbarcelos/ESP32_BLE_Keyboard.git
      #    arduino-cli lib install "ArduinoJson@7.2.0"
      #    arduino-cli lib install "ESPping@1.0.4"
      #    arduino-cli lib install "PubSubClient@2.8"
      #    arduino-cli lib install --git-url https://github.com/me-no-dev/AsyncTCP.git
      #    arduino-cli lib install --git-url https://github.com/marvinroger/async-mqtt-client.git

      - name: Install libraries
        run: |
          arduino-cli lib install --git-url https://github.com/allanbarcelos/ESP32_BLE_Keyboard.git
          arduino-cli lib install "ArduinoJson@7.2.0"

      - name: Generate secrets.h
        run: |
          echo '#ifndef SECRETS_H' > secrets.h
          echo '#define SECRETS_H' >> secrets.h
          echo '' >> secrets.h
          echo 'const char* ssid = "${{ secrets.WIFI_SSID }}";' >> secrets.h
          echo 'const char* password = "${{ secrets.WIFI_PASS }}";' >> secrets.h
          echo "const char* firmware_version = \"v${{ github.run_number }}\";" >> secrets.h

          echo "const char* cf_token = \"v${{ github.run_number }}\";" >> secrets.h
          echo "const char* cf_zone = \"v${{ github.run_number }}\";" >> secrets.h
          echo "const char* cf_record = \"v${{ github.run_number }}\";" >> secrets.h
          echo "const char* cf_host = \"v${{ github.run_number }}\";" >> secrets.h

          echo '' >> secrets.h
          echo '#endif' >> secrets.h

      - name: Compile firmware (ESP32 Generic)
        id: build
        run: |
          set -e  # interrompe se qualquer comando falhar
          mkdir -p build
          echo "Compilando firmware para ESP32..."

          arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --output-dir build \
            --build-property build.flags.optimize.lto=true \
            --build-property build.flags.optimize.size=true \
            --warnings all \
            --verbose

          echo "Compilação concluída."
          ls -lh build

      - name: Rename and Export firmware
        run: |
          set -e
          BIN_FILE=$(find build -maxdepth 1 -name "*.bin" -print -quit)
          if [ -z "$BIN_FILE" ]; then
            echo "Nenhum arquivo .bin encontrado!"
            exit 1
          fi
          mv "$BIN_FILE" build/firmware.bin
          echo "FIRMWARE_BIN=build/firmware.bin" >> $GITHUB_ENV
          echo "Arquivo final: build/firmware.bin"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: ${{ env.FIRMWARE_BIN }}

      - name: Create GitHub Release and upload firmware
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: ESP32 Firmware Build ${{ github.run_number }}
          files: ${{ env.FIRMWARE_BIN }}
          generate_release_notes: false
